apiVersion: v1
kind: Pod
metadata:
  name: minesweeper-gui
spec:
  restartPolicy: Never
  containers:
    - name: gui
      image: minesweeper/novnc
      imagePullPolicy: Never
      ports:
        - containerPort: 6080

